apiVersion: apps/v1
kind: Deployment
metadata:
  name: carapplication-deployment
  labels:
    app: carapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: carapp
  template:
    metadata:
      labels:
        app: carapp 
    spec:
      containers:
      - name: nodeserver
        image: aktohme/carapp:latest
        ports:
        - containerPort: 8802