apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: carapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8803
    targetPort: 8802
    nodePort: 31110